### ISSUE TITLE
Doesn't work in repeater fields

### ISSUE THREAD

**Issue by bfncs** [bfncs/TextareaCounter#1]
The inputfield currently does not work as part of a repeater field.

**Comment by tbba** [comment]
Any news here?

**Comment by bfncs** [comment]
@juagarc4 built a patch that is reported to fix it:

https://github.com/juagarc4/TextareaCounter/commit/3d01657e0e46b67f211719ec1fd4b6b2fb5c85da

Didn't find the time though to review and merge it, but it should do the job.
